- hosts: localhost
  vars:
    dotfiles_path: /home/{{ user }}/.dotfiles
  
  tasks:
    - name: Upgrade system packages
      dnf:
        name: "*"
        state: latest

    - name: Add user specific packages
      dnf:
        name:
          - code
          - alacritty
          - feh
          - xrandr
          - conky
          - rofi
          - tmux
          - xss-lock
          - ImageMagick
          - stow
          - neovim, python3-neovim
          - newsboat
          - picom
          - pavucontrol
          - redshift, redshift-gtk
          - maim
          - xclip
          - xdotool

    - name: Fetch dotfiles git repository
      become: true
      become_user: "{{ user }}"
      git:
        repo: 'https://github.com/YannLebouc/.dotfiles.git'
        dest: "{{ dotfiles_path }}"

    - name: Make symbolic links with dotfiles
      become: true
      become_user: "{{ user }}"
      command:
        cmd: "{{ dotfiles_path }}/.config-symlinks.sh"
